// src/components/common/Podium.tsx
import React from "react";
import Card from "./Card";

import firstPlaceImage from "../../assets/images/first_place.png";
import secondPlaceImage from "../../assets/images/second_place.png";
import thirdPlaceImage from "../../assets/images/third_place.png";

interface PodiumProps {
  title?: React.ReactNode;
  firstPlace: {
    name: React.ReactNode;
    stat: React.ReactNode;
  };
  secondPlace: {
    name: React.ReactNode;
    stat: React.ReactNode;
  };
  thirdPlace: {
    name: React.ReactNode;
    stat: React.ReactNode;
  };
  seeMoreButton?: React.ReactNode;
}

export default function Podium({
  title,
  firstPlace,
  secondPlace,
  thirdPlace,
  seeMoreButton,
}: PodiumProps) {
  return (
    <div className="flex flex-col md:flex-wrap justify-center lg:grid">
      {title && <div className="text-3xl mb-2">{title}</div>}

      <div className="flex justify-center items-end">
        {/* Second place */}
        <Card
          title={
            <div className="flex justify-center">
              <img
                src={secondPlaceImage}
                alt="Second Place (freepik icon)"
                className="mt-2 w-[35%]"
              />
            </div>
          }
          body={
            <div className="text-2xl text-center pt-6 pb-2">
              {secondPlace.name}
            </div>
          }
          footer={<div className="text-center w-full">{secondPlace.stat}</div>}
          className="bg-primary text-base-100 w-75 mr-2 min-h-75 rounded"
          cardBodyClassName="card-body"
          titleClassName=""
          bodyClassName=""
        />

        {/* First place */}
        <Card
          title={
            <div className="flex justify-center">
              <img
                src={firstPlaceImage}
                alt="First Place (freepik icon)"
                className="mt-2 w-[40%]"
              />
            </div>
          }
          body={
            <div className="text-3xl text-center pt-8 pb-2">
              {firstPlace.name}
            </div>
          }
          footer={<div className="text-center w-full">{firstPlace.stat}</div>}
          className="bg-primary text-base-100 w-75 min-h-100 rounded"
          cardBodyClassName="card-body"
          titleClassName=""
          bodyClassName=""
        />

        {/* Third place */}
        <Card
          title={
            <div className="flex justify-center">
              <img
                src={thirdPlaceImage}
                alt="Third Place (freepik icon)"
                className="mt-2 w-[30%]"
              />
            </div>
          }
          body={
            <div className="text-xl text-center pt-4 pb-2">
              {thirdPlace.name}
            </div>
          }
          footer={<div className="text-center w-full">{thirdPlace.stat}</div>}
          className="bg-primary text-base-100 w-75 ml-2 min-h-62.5 rounded"
          cardBodyClassName="card-body"
          titleClassName=""
          bodyClassName=""
        />
      </div>

      {/* Optional see more button */}
      {seeMoreButton && (
        <div className="btn btn-soft btn-primary mt-2">{seeMoreButton}</div>
      )}
    </div>
  );
}

// src/lib/components/Podium.svelte
<script lang="ts">
    import { Avatar } from "@skeletonlabs/skeleton";

    const firstPlaceImage = "/images/first_place.png"
    const secondPlaceImage = "/images/second_place.png"
    const thirdPlaceImage = "/images/third_place.png"

</script>

<div class="flex flex-col md:flex-wrap justify-center lg:grid">

    <slot name="title" />
    
    <div class="flex justify-center items-end">
    
        <!-- Second place -->
        <div class="card card-hover w-[300px] mr-2 min-h-[300px]">
            <header class="flex justify-center card-header">
                <Avatar src={secondPlaceImage} alt="Second Place (freepik icon)" class="mt-2" width="w-[35%]" rounded="none" background="none" />
            </header>
            <section class="text-2xl text-center pt-6 pb-2">
                <slot name="secondPlaceName" />
            </section>
            <footer class="card-footer text-center">
                <slot name="secondPlaceStat" />
            </footer>
        </div>
    
        <!-- First place -->
        <div class="card card-hover w-[300px] min-h-[400px]">
            <header class="flex justify-center card-header">
                <Avatar src={firstPlaceImage} alt="First Place (freepik icon)" class="mt-2" width="w-[40%]" rounded="none" background="none" />
            </header>
            <section class="text-3xl text-center pt-8 pb-2">
                <slot name="firstPlaceName" />
            </section>
            <footer class="card-footer text-center">
                <slot name="firstPlaceStat" />
            </footer>
        </div>
    
        <!-- Third place -->
        <div class="card card-hover w-[300px] ml-2 min-h-[250px]">
            <header class="flex justify-center card-header">
                <Avatar src={thirdPlaceImage} alt="Third Place (freepik icon)" class="mt-2" width="w-[30%]" rounded="none" background="none" />
            </header>
            <section class="text-xl text-center pt-4 pb-2">
                <slot name="thirdPlaceName" />
            </section>
            <footer class="card-footer text-center">
                <slot name="thirdPlaceStat" />
            </footer>
        </div>
    </div>

    <!-- See more button -->
    <slot name="seeMoreBtn" />
</div>
